default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

build-debug:
  stage: build
  script:
  - dotnet build -c Debug

build-release:
  stage: build
  artifacts:
    paths:
      - PaintDrops/
      
  script:
  - dotnet publish -c Release -r win-x64 --self-contained true -o ./PaintDrops
  - tar -cvf PaintDrops.tar ./PaintDrops/*

Test:
  stage: test
  script:
  - dotnet test