default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

build-debug:
  stage: build
  script:
    - apt-get -y update
    - apt-get -y install libfreetype6
    - dotnet build -c Debug

build-release:
  stage: build
  artifacts:
    paths:
      - Game.tar
      
  script:
    - apt-get -y update
    - apt-get -y install libfreetype6
    - dotnet publish -c Release -r win-x64 --self-contained false -o ./PaintDropsArtifact
    - cd ./PaintDropsArtifact
    - tar -cvf ../Game.tar *

Test:
  stage: test
  script:
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./artifacts/ShapeLibraryTests-test result.xml
    reports:
      junit:
        - ./artifacts/ShapeLibraryTests-test result.xml
