default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

build-debug:
  stage: build
  script:
  - dotnet build -c Debug

build-release:
  stage: build
  artifacts:
    paths:
      - PaintDrops/
      
  script:
  - dotnet publish -c Release -r win-x64 --self-contained true -o ./PaintDropsArtifact
  - tar -cvf Game.tar ./PaintDropsArtifact/*

Test:
  stage: test
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
